import json
import os
import nukleus.scons as nukleus

from SCons.Node import NodeList



env = Environment(ENV=os.environ,
                  tools=['default', nukleus.generate],
                  NUKLEUS_ENVIRONMENT_VARS={'pcb': {}},
                  NUKLEUS_TARGETS={'pcb': {
                        'layers': [
                            'F.Cu',
                            'B.Cu',
                            'In1.Cu',
                            'In2.Cu',
                            'In3.Cu',
                            'In4.Cu',
                            'In5.Cu',
                            'In6.Cu',
                            'F.SilkS',
                            'B.SilkS',
                            'F.Mask',
                            'B.Mask',
                            'Edge.Cuts',
                        ],
                      },
                      'schema': {},
                      'bom': {},
                      'gerbers': {},
                      },
                  NBCONVERT_ENVIRONMENT_VARS={'flags': ['execute', 'no-input'],
                                              'to': 'html',
                                              'log-level': 'CRITICAL',
                                              'ExecutePreprocessor.kernel_name': 'python3',
                                              'HTMLExporter.exclude_anchor_links': True,
                                              'template': 'hugo',
                                              'TemplateExporter.extra_template_basedirs': '/templates/',
                                              'TemplateExporter.exclude_output_prompt': True,
                                              'TemplateExporter.exclude_output_stdin': True}
                  )

REPORTS = NodeList()

env.nukleus('target/main', 'main.kicad_pro')
#env.schema('main_schema.pdf', 'main.kicad_sch')
#REPORTS += env.bom('main.bom', 'main.kicad_sch', project_name="summe")
#REPORTS += env.drc('main_drc.json', 'main.kicad_pcb', project_name="summe")
#REPORTS += env.erc('main_erc.json', 'main.kicad_sch', project_name="summe")
#env.gerbers('main_pcb.zip', 'main.kicad_pcb')
#env.pcb('main_pcb.pdf', 'main.kicad_pcb')
#env.reports('report.json', REPORTS)
#env.report2xunit('content/report.xml', 'content/report.json')
